CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD(
	boardNum NUMBER(38),
	boardTitle VARCHAR2(2000),
	boardContent VARCHAR2(2000),
	boardId VARCHAR2(2000),
	boardDate DATE DEFAULT SYSDATE,
	readCount NUMBER(38) DEFAULT 0,
	CONSTRAINT PK_BOARD PRIMARY KEY(boardNum),
	CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(boardId)
	REFERENCES TBL_MEMBER(memberId)
);

SELECT * FROM TBL_BOARD;

INSERT INTO TBL_BOARD
(BOARDNUM, BOARDTITLE, BOARDCONTENT, BOARDID)
VALUES(SEQ_BOARD.NEXTVAL, '테스트1', '테스트내용1', 'hds1');

INSERT INTO TBL_BOARD
SELECT SEQ_BOARD.NEXTVAL, BOARDTITLE, BOARDCONTENT, BOARDID, SYSDATE, 0 FROM TBL_BOARD;

	SELECT * FROM
		(
		SELECT ROWNUM R, B.* FROM
			(SELECT * FROM TBL_BOARD ORDER BY BOARDNUM DESC) B
		WHERE ROWNUM <= 10
		)
		WHERE R >= 1;
