CREATE TABLE TBL_FILES(
	fileName VARCHAR2(2000) PRIMARY KEY,
	boardNum NUMBER(38),
	fileNameOriginal VARCHAR2(2000),
	CONSTRAINT FK_FILES_BOARD FOREIGN KEY(boardNum)
	REFERENCES TBL_BOARD(boardNum)
);

SELECT * FROM TBL_FILES;

