CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
	replyNum NUMBER(38),
	boardNum NUMBER(38),
	memberId VARCHAR2(1000),
	replyContent VARCHAR2(2000),
	CONSTRAINT PK_REPLY PRIMARY KEY(replyNum),
	CONSTRAINT FK_REPLY_BOARD FOREIGN KEY(boardNum)
	REFERENCES TBL_BOARD(boardNum) ON DELETE CASCADE
);

INSERT INTO TBL_REPLY
(REPLYNUM, BOARDNUM, MEMBERID, REPLYCONTENT)
VALUES(SEQ_REPLY.NEXTVAL, 271, 'hds1', 'Å×½ºÆ® ´ñ±Û');

SELECT * FROM TBL_REPLY;