CREATE TABLE TABLE_MEMBER(
	ID VARCHAR2(500) PRIMARY KEY,
	PW VARCHAR2(500),
	NAME VARCHAR2(500),
	AGE NUMBER(3)
);

SELECT * FROM TABLE_MEMBER;

UPDATE TABLE_MEMBER
SET AGE = 30
WHERE NAME = 'ÇÑµ¿¼®';